### ISSUE TITLE
Captcha doesn't always show when it should

### ISSUE THREAD

**Issue by forevermatt** [silinternational/simplesamlphp-module-silauth#24]
If you use different usernames and fail enough login attempts that captcha is required, it doesn't (or doesn't always?) show the reCaptcha... but since it was required, even valid credentials will fail at that point because a valid captcha response wasn't provided.

**Comment by longrunningprocess** [comment]
I'll need to look at that a little more closely then because I would assume whether Google decides to force the user to solve something or not, the reCAPTCHA response would still be sent when we include it.  Did you happen to notice any browser console errors in the process, e.g., the reCAPTCHA didn't load?

**Comment by forevermatt** [comment]
I think the problem is purely within SilAuth. It's simply not adding the reCaptcha stuff to the webpage at all (sometimes), even when it's going to require it.

**Comment by forevermatt** [comment]
This was resolved by 000f7bc.
